---
k3s_server_config: {}

k3s_server_config_base:
  data-dir: "{{ data_dir }}"
  node-ip: "{{ k3s_node_ip }}"
  node-name: "{{ ansible_fqdn }}"
  cluster-domain: "{{ cluster_domain }}"
  cluster-cidr: "{{ cluster_cidr }}"
  service-cidr: "{{ service_cidr }}"
  token: "{{ k3s_token }}"
  tls-san:
    - "{{ apiserver_endpoint }}"

k3s_kubectl_binary: k3s kubectl

group_name_master: master

k3s_create_kubectl_symlink: true
k3s_create_crictl_symlink: true

retry_count: 20

systemd_dir: /etc/systemd/system
