---
argument_specs:
  main:
    short_description: Setup k3s agents
    options:
      apiserver_endpoint:
        description: Virtual ip-address configured on each master
        required: true

      k3s_token:
        description: Shared secret used to join nodes to the cluster
        required: true

      # TODO: Add argument specs for data_dir, k3s_node_ip

      k3s_agent_config:
        description: Additional k3s agent config merged into /etc/rancher/k3s/config.yaml
        type: dict
        default: {}

      group_name_master:
        description: Name of the master group
        default: master

      proxy_env:
        type: dict
        description:
          - Internet proxy configurations.
          - See https://docs.k3s.io/advanced#configuring-an-http-proxy for details
        default: ~
        options:
          HTTP_PROXY:
            description: HTTP internet proxy
            required: true
          HTTPS_PROXY:
            description: HTTPS internet proxy
            required: true
          NO_PROXY:
            description: Addresses that will not use the proxies
            required: true

      systemd_dir:
        description: Path to systemd services
        default: /etc/systemd/system
