---
k3s_kubectl_binary: k3s kubectl

group_name_master: master

cilium_bgp: false
cilium_export_pod_cidr: true

cilium_bgp_my_asn: 64513
cilium_bgp_peer_asn: 64512
cilium_bgp_neighbors: []
cilium_bgp_neighbors_groups: ['k3s_all']
cilium_bgp_lb_cidr: 192.168.31.0/24

cilium_bgp_ebgp_multihop: 1
cilium_bgp_graceful_restart: false
cilium_bgp_graceful_restart_secs: 120
cilium_bgp_timer_connect_retry_secs: 120
cilium_bgp_timer_hold_secs: 90
cilium_bgp_timer_keepalive_secs: 30
