---
- name: Stop and disable k3s services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  with_items:
    - k3s
    - k3s-agent
    - k3s-init

- name: Kill containerd-shim-runc processes
  register: pkill_containerd_shim_runc
  ansible.builtin.command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: pkill_containerd_shim_runc.rc == 0
  failed_when: false

- name: Umount k3s filesystems
  ansible.builtin.include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
    - /var/lib/kubelet/pods
    - /var/lib/kubelet/plugins
    - /run/netns/cni-
    - "{{ data_dir }}"
  loop_control:
    loop_var: mounted_fs

- name: Remove k3s files, binaries, and data
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-agent.service"
    - /etc/rancher/k3s
    - /run/k3s
    - /run/flannel
    - /etc/rancher/
    - /var/lib/kubelet
    - /var/lib/rancher/k3s
    - /var/lib/rancher/
    - /var/lib/cni/
    - /etc/cni/net.d
    - "{{ data_dir }}"

- name: Remove k3s HTTP proxy files
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ systemd_dir }}/k3s.service.d/http_proxy.conf"
    - "{{ systemd_dir }}/k3s.service.d"
    - "{{ systemd_dir }}/k3s-agent.service.d/http_proxy.conf"
    - "{{ systemd_dir }}/k3s-agent.service.d"
  when: proxy_env is defined

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Remove temporary manifests directory
  ansible.builtin.file:
    path: /tmp/k3s
    state: absent
