---
- name: Configure Cilium BGP on first master
  when:
    - ansible_hostname == hostvars[groups[group_name_master][0]]['ansible_hostname']
    - cilium_bgp
  run_once: true
  block:
    - name: Create temporary directory on first master
      ansible.builtin.file:
        path: /tmp/k3s
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Merge Cilium BGP neighbors
      ansible.builtin.set_fact:
        _cilium_bgp_neighbors: >-
          {{ lookup('community.general.merge_variables',
                    '^cilium_bgp_neighbors__.+$',
                    initial_value=cilium_bgp_neighbors,
                    groups=cilium_bgp_neighbors_groups) }}

    - name: Delete v1 CiliumBGPPeeringPolicy
      ansible.builtin.command:
        cmd: >-
          {{ k3s_kubectl_binary }} delete CiliumBGPPeeringPolicy
          bgp-peering-policy --ignore-not-found
      register: delete_v1
      changed_when: ('deleted' in delete_v1.stdout)
      failed_when: delete_v1.rc != 0 and "doesn't have a resource type" not in delete_v1.stderr

    - name: Label all nodes for BGP peering
      ansible.builtin.command:
        cmd: >-
          {{ k3s_kubectl_binary }} label node
          {{ hostvars[item]['ansible_fqdn'] }}
          bgp-enabled=true --overwrite
      loop: "{{ groups['k3s_cluster'] }}"
      changed_when: false

    - name: Copy BGP manifests to first master
      ansible.builtin.template:
        src: resources.yaml.j2
        dest: /tmp/k3s/cilium-bgp.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Apply BGP manifests
      ansible.builtin.command:
        cmd: "{{ k3s_kubectl_binary }} apply -f /tmp/k3s/cilium-bgp.yaml"
      register: apply_cr
      changed_when: ('configured' in apply_cr.stdout or 'created' in apply_cr.stdout)
      failed_when: ('is invalid' in apply_cr.stderr)
      ignore_errors: true

    - name: Log BGP manifest errors
      ansible.builtin.debug:
        msg: "{{ apply_cr.stderr }}"
      when: ('is invalid' in apply_cr.stderr)

    - name: Verify BGP config resources
      ansible.builtin.command: "{{ item }}"
      loop:
        - "{{ k3s_kubectl_binary }} get CiliumBGPClusterConfig.cilium.io"
        - "{{ k3s_kubectl_binary }} get CiliumBGPPeerConfig.cilium.io"
        - "{{ k3s_kubectl_binary }} get CiliumBGPAdvertisement.cilium.io"
        - "{{ k3s_kubectl_binary }} get CiliumLoadBalancerIPPool.cilium.io"
      changed_when: false
      loop_control:
        label: "{{ item }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: /tmp/k3s
        state: absent
