---
- name: Create k3s config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Add cluster-init for first server
  when:
    - (groups[group_name_master] | length) > 1
    - ansible_hostname == hostvars[groups[group_name_master][0]]['ansible_hostname']
  ansible.builtin.set_fact:
    k3s_server_config_base: "{{ k3s_server_config_base | combine(_extra) }}"
  vars:
    _extra:
      cluster-init: true

# TODO: don't hardcode port 6443
- name: Add server URL for joining servers
  when:
    - (groups[group_name_master] | length) > 1
    - ansible_hostname != hostvars[groups[group_name_master][0]]['ansible_hostname']
  ansible.builtin.set_fact:
    k3s_server_config_base: "{{ k3s_server_config_base | combine(_extra) }}"
  vars:
    _extra:
      server: "https://{{ apiserver_endpoint }}:6443"

- name: Add node taint for control plane
  when: k3s_master_taint | bool
  ansible.builtin.set_fact:
    k3s_server_config_base: "{{ k3s_server_config_base | combine(_extra) }}"
  vars:
    _extra:
      node-taint:
        - "node-role.kubernetes.io/control-plane:NoSchedule"

- name: Merge server config overrides
  when: k3s_server_config is defined
  ansible.builtin.set_fact:
    k3s_server_config_base: >-
      {{ k3s_server_config_base | combine(k3s_server_config, recursive=true) }}

- name: Write config.yaml
  ansible.builtin.copy:
    content: "{{ k3s_server_config_base | to_nice_yaml }}"
    dest: /etc/rancher/k3s/config.yaml
    mode: "0640"
  register: _k3s_config_result

- name: Deploy k3s HTTP proxy config
  ansible.builtin.include_tasks: http_proxy.yml
  when: proxy_env is defined

- name: Install k3s service unit
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: "0644"
  register: _k3s_service_unit

- name: Enable and start k3s
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: "{{ 'restarted' if (_k3s_config_result.changed or _k3s_service_unit.changed) else 'started' }}"
    enabled: true

- name: Wait for first server API readiness
  when: ansible_hostname == hostvars[groups[group_name_master][0]]['ansible_hostname']
  ansible.builtin.wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    timeout: 120

# TODO: need a better means of verifying it's ready
- name: Pause to allow first server startup
  when:
    - (groups[group_name_master] | length) > 1
    - ansible_hostname == hostvars[groups[group_name_master][0]]['ansible_hostname']
  ansible.builtin.pause:
    seconds: 10

- name: Verify all masters joined the cluster
  when:
    - not ansible_check_mode
    - (groups[group_name_master] | length) > 1
  ansible.builtin.command:
    cmd: >-
      {{ k3s_kubectl_binary }}
      get nodes
      -l 'node-role.kubernetes.io/control-plane'
      -o=jsonpath='{.items[*].metadata.name}'
  register: nodes
  until: >-
    nodes.rc == 0 and
    (nodes.stdout.split() | length) == (groups[group_name_master] | length)
  retries: "{{ retry_count }}"
  delay: 10
  changed_when: false

- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: u=rwx,g=rx,o=

- name: Copy kubeconfig to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    mode: u=rw,g=,o=

- name: Configure kubectl cluster to {{ endpoint_url }}
  ansible.builtin.command: >-
    {{ k3s_kubectl_binary }} config set-cluster default
      --server={{ endpoint_url }}
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true
  vars:
    endpoint_url: >-
      https://{{ apiserver_endpoint | ansible.utils.ipwrap }}:6443
# noqa jinja[invalid]

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
  when: k3s_create_kubectl_symlink | bool

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
  when: k3s_create_crictl_symlink | bool
